package com.example.fitnessMarathonBot.botapi;

/**Возможные состояния бота
 */

public enum BotState {
    ASK_START,
    SHOW_MAIN_MENU,
    ASK_PERSONAL_INFO,
    ASK_HEIGHT,
    ASK_WEIGHT,
    ASK_PHYSIQUE,
    ASK_AGE,
    ASK_NAME,

    ADMIN_MAIN_MENU,
    SHOW_ADMIN_MAIN_MENU,
    ASK_ADMIN_START,
    VIEW_PARTICIPANTS_ADN_RESULTS,
    START_NEW_MARATHON,
    REFRESH_GOALS,
    ANSWER_THE_QUESTIONS,


    MAIN_MENU,
    REPORT_OF_THE_DAY,
    SHOW_REPORT_OF_THE_DAY,
    SHOW_CHAT_WITH_MANAGER,
    SHOW_PLAN_FOR_TODAY,
    PLAN_FOR_TODAY,
    MY_INFORMATION,
    WRITE_TO_MANAGER,
    PROFILE_FILLED,

    SHOW_LIST_TRAINING,
    LIST_TRAINING
}
