package com.example.fitnessMarathonBot.botapi;

/**Возможные состояния бота
 */

public enum BotState {
    ASK_START,
    SHOW_MAIN_MENU,
    ASK_PERSONAL_INFO,
    ASK_HEIGHT,
    ASK_WEIGHT,
    ASK_PHYSIQUE,
    ASK_AGE,
    ASK_NAME,
    ASK_ARM,
    ASK_SHIN,
    ASK_BELLY,
    ASK_CHEST,
    ASK_WAIST,
    ASK_THIGH,
    ASK_THIGHS,
    ASK_NECK,
    ASK_DATE,

    ADMIN_MAIN_MENU,
    SHOW_ADMIN_MAIN_MENU,
    VIEW_PARTICIPANTS_ADN_RESULTS,
    START_NEW_MARATHON,
    REFRESH_GOALS,
    ANSWER_THE_QUESTIONS,


    MAIN_MENU,
    REPORT_OF_THE_DAY,
    SHOW_CHAT_WITH_MANAGER,
    TASK,
    MY_INFORMATION,
    LINK_TO_CHAT,
    PROFILE_FILLED,
}
